const mongoose = require('mongoose')

const chorinstanceSchema = mongoose.Schema({
  idModel: mongoose.Schema.Types.ObjectId,                // id choreography model (EthUsers db)
  idChorLedger: String,                                   // key of the choreography fabric ledger state (generated by the translator)
  // idBpmnFile: String,
  // idChor: String,                                      // e.g. 'CHOR1'
  // bpmnFileName: String,
  startEvent: String,                                     // e.g. 'Event_0tttznh'
  roles: Object,                                          // e.g. { Customer: 'Org1MSP', Bike_center: 'Org2MSP', Insurer: 'Org3MSP' }
  contractName: String,                                   // e.g. 'org.chorchain.choreographyprivatedata_1'
  channel: String,                                        // e.g. 'channel123'
  configTxProfile: String,                                // e.g. 'OrgsChannel'
  contractVersion: Number,
  created_at: { type: Date, required: true, default: Date.now },
  deployed: { type: Boolean, default: false },            // contract deployed into blockchain net (true), not deployed otherwise (false)
  idUsersSubscribed: [mongoose.Schema.Types.ObjectId],    // array of subscribed users, default empty
  subscriptions: Object                                   // mapping object between user ids (string) and roles e.g. { Customer: 'idUser1', Bike_center: null, Insurer: null }
})

module.exports = mongoose.model('fabchorinstance', chorinstanceSchema)
